spring:
  datasource:
    url: jdbc:mysql://localhost:3306/food_deliveryjpa
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect:spring.jpa.properties.hibernate.MySQL8dialect
        ddl-auto=create
    show-sql: true
    
server:
  port: 9005
 
    
zee5app:
  app:
    jwtSecret: secretkey
    jwtExpirationMs: 86400000